# Generated by Django 4.2.3 on 2023-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
